### ISSUE TITLE
Gitlab CI/CD failing to build react app with latest version (docker environment)

### ISSUE THREAD

**Issue by clementcorreia** [mhart/alpine-node#155]
My pipeline in Gitlab CI/CD is failing since the push of the new version (alpine-node:latest or 15.0.1).

There are no more logs than the screen below.

![image](https://user-images.githubusercontent.com/22796283/97746469-a7834700-1aea-11eb-8d50-bff4d19335b8.png)

### Environment
*  docker:19.0.13-dind
*  react with create-react-app
*  Gitlab CI/CD

### Extract of my gitlab-ci
```yaml
image: docker:19.03.13-dind

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:19.03.13-dind

stages:
  - Build
  - Deploy

build_test:
  stage: Build
  only:
    - test
    - /^release\/v[0-9]+\.[0-9]+\.[0-9]+(-beta)?$/
  script:
    - version=`echo $CI_COMMIT_BRANCH | cut -c9-`
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
    - docker build -t "$CI_REGISTRY_IMAGE_FRONT:test" -f ./front-si-reactjs/DockerfileTest ./front-si-reactjs
    - docker build -t "$CI_REGISTRY_IMAGE_API:test" -f ./api/DockerfileProd ./api
    - docker push "$CI_REGISTRY_IMAGE_FRONT"
    - docker push "$CI_REGISTRY_IMAGE_API"
```

### Dockerfile
```
FROM mhart/alpine-node:latest as react-build
WORKDIR /app
COPY ./package*.json ./
RUN npm install --silent && npm audit fix --silent
COPY . ./
RUN npm run build --silent

# Stage 2 - the production environment
FROM mhart/alpine-node:latest
COPY --from=react-build /app/build /usr/src/app
RUN npm install -g serve
CMD ["serve", "-s", "/usr/src/app", "-l", "3000"]
```

### Workaround

I've fixed the issue by rolling back the alpine node version to 14.15.0
