### ISSUE TITLE
No node_modules directory

### ISSUE THREAD

**Issue by eltoro** [mhart/alpine-node#60]
I'm sure I'm doing something wrong but I'm using docker-compose to run this Dockerfile and it ins't installing the node_module directory unless I do an npm install locally. I'm using compose because I'll be adding a few more services. Am I missing something?

```
FROM mhart/alpine-node:6
MAINTAINER Me

COPY package.json index.js lib /app/

WORKDIR /app

RUN apk add --no-cache make gcc g++ python && \
  addgroup -S app && adduser -S -g app app && \
  npm install && \
  npm cache clean && \
  apk del make gcc g++ python

USER app
```

And my docker-compose.yml:

```
version: "2"
services:
  gateway:
    build: .
    command: npm start
    container_name: gateway
    volumes:
      - .:/app
    ports:
     - "8787:8787"
    networks:
      - harmony-net

networks:
    harmony-net:
      driver: bridge
```
